---
- name: Ensure Istio control plane namespace exists
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ sm_namespace }}'
        annotations:
          openshift.io/display-name: '{{ sm_ns_display|default(omit) }}'
      spec: {}

- name: Subscribe to Service Mesh and prerequisites
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "subscriptions.yml.j2")|from_yaml }}'

- name: Deploy Service Mesh Control PLane
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "control_plane.yml.j2")|from_yaml }}'
  register: control_plane_deployment
  until: not control_plane_deployment.failed
  retries: 5
  delay: 10

- name: Configure 3scale istio adapter
  import_tasks: 3scale_adapter.yml
  when: deploy_3scale|default(true)
